---
version: 2.1

executors:
  go-build:
    docker:
      - image: circleci/golang:1.14

commands:
  save-go-mod-cache:
    steps:
      - save_cache:
          key: v1-dependencies-{{ checksum "go.sum" }}
          paths:
            - /go/pkg/mod

  restore-go-mod-cache:
    steps:
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "go.sum" }}

  save-workspace:
    steps:
      - persist_to_workspace:
          root: .
          paths:
            - ./

  restore-workspace:
    steps:
      - attach_workspace:
          at: .

jobs:
  test:
    executor: go-build
    steps:
      - checkout
      - restore-go-mod-cache
      # commands
      - run: |
          git config --global user.email circleci
          git config --global user.name circleci
      - run: make deps-coverage
      - run: go get
      - run: make test-circle
      - run: make build
      # persist
      - save-go-mod-cache
      - save-workspace

  release:
    executor: go-build
    steps:
      - setup_remote_docker
      - restore-workspace
      - restore-go-mod-cache
      # commands
      - run: docker login -u "$QUAY_USER" -p "$QUAY_PASSWD" quay.io
      - run: sudo apt-get -qqy update && sudo apt-get -qqy install rpm
      - run: |
          # ./autotag/autotag binary from the test job is not saved to the workspace with +x bit, restore it
          chmod +x ./autotag/autotag
      - run: ./autotag/autotag
      - run: curl -sL https://git.io/goreleaser | bash -s -- --parallelism=2

workflows:
  version: 2
  primary:
    jobs:
      - test
      - release:
          requires:
            - test
          filters:
            branches:
              only:
                - master
